/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, KnowledgeBase as PrismaKnowledgeBase } from "@prisma/client";

export class KnowledgeBaseServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.KnowledgeBaseCountArgs, "select">
  ): Promise<number> {
    return this.prisma.knowledgeBase.count(args);
  }

  async knowledgeBases(
    args: Prisma.KnowledgeBaseFindManyArgs
  ): Promise<PrismaKnowledgeBase[]> {
    return this.prisma.knowledgeBase.findMany(args);
  }
  async knowledgeBase(
    args: Prisma.KnowledgeBaseFindUniqueArgs
  ): Promise<PrismaKnowledgeBase | null> {
    return this.prisma.knowledgeBase.findUnique(args);
  }
  async createKnowledgeBase(
    args: Prisma.KnowledgeBaseCreateArgs
  ): Promise<PrismaKnowledgeBase> {
    return this.prisma.knowledgeBase.create(args);
  }
  async updateKnowledgeBase(
    args: Prisma.KnowledgeBaseUpdateArgs
  ): Promise<PrismaKnowledgeBase> {
    return this.prisma.knowledgeBase.update(args);
  }
  async deleteKnowledgeBase(
    args: Prisma.KnowledgeBaseDeleteArgs
  ): Promise<PrismaKnowledgeBase> {
    return this.prisma.knowledgeBase.delete(args);
  }
}
